# Generated by Django 5.1.4 on 2025-01-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='employee_id',
            new_name='login_id',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='is_leader',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
