# Generated by Django 5.1.4 on 2025-01-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_employee_id_employeeprofile_login_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
